In [ ]:
import numpy as np 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns

In [ ]:
df = sns.load_dataset('diamonds')
df.head()

In [ ]:
df = df.drop(['cut', 'color', 'clarity'], axis = 1) # Only considering the numerical features for linear regression

In [ ]:
X = df.drop(['price'], axis=1);y = df['price']
X.head(), y.head()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.2,
    random_state=42,
    shuffle=True
)

In [ ]:
# standard scaler 
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled

In [ ]:
model = LinearRegression(fit_intercept=True)
model.fit(x_train_scaled, y_train)

In [ ]:
model.intercept_, model.coef_

In [ ]:
## Build the gradient descant alogrith from scratch
# Linear equation = y = b1*x1 + b2*x2 + b3*x3 + b4*x4 + b5*x5 + b6*x6 + b0 this will be my linear equation 
Y = B*X
## LOSS Function = (1/n)np.sum((y_hat - yi)**2)

In [ ]:
n, m = x_train_scaled.shape
print(n, m) # these are my number of rows and columns 

In [142]:
weights = np.zeros((m,1))
bias = np.zeros(1)
print(weights, bias)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] [0.]


In [164]:
y_hat = np.dot(x_train_scaled, weights.ravel()) + bias 
error = y_hat - y_train
# gradient descant 
weights = weights - (2/n)*0.1*(np.dot(error,x_train_scaled)).reshape(weights.shape)
bias = bias -(2/n)*0.1*(np.sum(error))

In [ ]:
beta_0.shape

In [165]:
weights, bias

(array([[-9.46469560e+40],
        [-1.27542530e+41],
        [ 1.01144046e+41],
        [-8.90205299e+40],
        [-8.81289171e+40],
        [-1.03880023e+41]]),
 array([-7.74882657e+41]))

In [ ]:
np.dot(weights,x_train_scaled[0])

In [ ]:
x_test_scaled = scaler.transform(x_test)

In [ ]:
for epoch in range(20):
    alpha = 0.5
    # Loop through every single row (data point) in the dataset
    for i in range(n):
        # 1. Predict for row i (Shape: scalar)
        y_hat = np.dot(x_train_scaled[i], weights.ravel()) + beta_0
        
        # 2. Calculate error for row i (Shape: scalar)
        error = y_hat - y_train.iloc[i]
        
        # 3. Update all weights simultaneously using row i's features
        # For SGD, the sample size per update is 1, so the constant is 2 (not 2/n)
        weights = weights - (2 * alpha * error * x_train_scaled[i]).reshape(weights.shape)
        
        # 4. Update bias
        beta_0 = beta_0 - (2 * alpha * error)

In [ ]:
weights , beta_0

In [ ]:
model.coef_ , model.intercept_

In [ ]:
weights.shape, x_train_scaled.shape

In [ ]:
# gradient descant = w = w0 - alpha (partial derivative of loss fucntion wrt w)

In [ ]:
x_train.ravel()

In [ ]:
# calculate the y_hat 
y_hat = np.dot(beta,)